spring.application.name=coreService
service.port=8081
# PostgreSQL DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/coreServiceDB
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate & JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

user-service.url=http://localhost:8080
spring.jackson.property-naming-strategy=SNAKE_CASE



# JWT secret key
security.jwt.secret-key =${JWT_SECRET:oM8HqvU0pUo7dUjP9XjVgxW5Fh7nC8i2O2eS4yH6gKc=}
security.jwt.expiration-time=3600000

spring.config.import=optional:file:.env[.properties]

spring.security.user.name=core-user-name
spring.security.user.password=core-secret